- hosts:
  - ec2-k8s-m2
  - ec2-k8s-m3
  become: yes
  tasks:
    - name: "Reset cluster"
      shell: "kubeadm reset -f"
    - name: "Fazendo join kubernetes master"
      shell: 
    - name: "Colocando no path da maquina o conf do kubernetes"
      shell: mkdir -p /var/lib/jenkins/.kube && sudo cp -f /etc/kubernetes/admin.conf /var/lib/jenkins/.kube/config && sudo chown 113:119 /var/lib/jenkins/.kube/config && export KUBECONFIG=/etc/kubernetes/admin.conf
#---
- hosts:
  - ec2-k8s-w1
  - ec2-k8s-w2
  - ec2-k8s-w3
  become: yes
  tasks:
    - name: "Reset cluster"
      shell: "kubeadm reset -f"
    - name: "Fazendo join kubernetes worker"
      shell: 
#---
- hosts:
  - ec2-k8s-m1
  become: yes
  tasks:
    - name: "Configura weavenet para reconhecer os nós master e workers"
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
